language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
services:
  - postgresql
env:
  - DATABASE_URL=postgresql://postgres@localhost:5432 NB_CONNECTION=1
cache: cargo
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - cargo install diesel_cli --no-default-features --features postgres
  - diesel setup
